### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by tomkail** [kmisiewicz/ahap-editor-unity#1]
Hi! Sorry for the dumb question!
When adding via github using `https://github.com/kmisiewicz/ahap-editor-unity.git` I get the following error:

`[Package Manager Window] Error adding package: https://github.com/kmisiewicz/ahap-editor-unity.git.
Unable to add package [https://github.com/kmisiewicz/ahap-editor-unity.git]:
  Error when executing git command. fatal: unable to access 'https://github.com/kmisiewicz/ahap-editor-unity.git/': Could not resolve host: github.com`

Any idea how to fix it?

**Comment by kmisiewicz** [comment]
Weird. Can you install any other package from git? Are you using a VPN or company network?

**Comment by tomkail** [comment]
Oh weird and now it works again 😅 At the time it was all github packages.
This tool is astoundingly good by the way! The graphing is insanely well done. The only thing missing is the ability to quickly preview on device, but I appreciate that's no easy feat.
I recommend looking at Hapticlabs Studio too; they're trialing a version of their app for mobile haptics which is very good.
